/* ============================================================
   MIAA — Traducciones EN/PT de los algoritmos nuevos
   Mapeadas por el texto ES canónico que vive en index.html
   (mismo patrón que aast/aast-trans.js y mip/mip-trans.js).
   El algoritmo original (decisión + Björck) ya es trilingüe vía I18N.
   Si una clave no existe, se muestra el español tal cual.
   ============================================================ */
window.MIAA_TRANS = {
en: {
  'Referencia':'Reference',
  /* --- Conducta según grado de Björck --- */
  'Conducta según grado de Björck':'Management by Björck grade',
  'Flujograma MIAA — Conducta según grado de Björck (curso MIAA)':'MIAA flowchart — Management by Björck grade (MIAA course)',
  '¿Hay adherencia o fijación de las vísceras a la pared?':'Is there adherence or fixation of the viscera to the abdominal wall?',
  'Define la vía: sin fijación (grados 1) permite cierre precoz; con fijación (grados 2) exige terapia de presión negativa primero.':'This sets the pathway: without fixation (grade 1) early closure is possible; with fixation (grade 2) negative-pressure therapy is required first.',
  'No — sin adherencia ni fijación':'No — no adherence or fixation',
  'Sí — con adherencia o fijación':'Yes — with adherence or fixation',
  'Abdomen congelado (frozen)':'Frozen abdomen',
  'Fístula enteroatmosférica (FEA)':'Enteroatmospheric fistula (EAF)',
  'Grado 1':'Grade 1','Grado 2':'Grade 2','Grado 3':'Grade 3','Grado 4':'Grade 4',
  '¿En qué estado está la cavidad?':'What is the state of the cavity?',
  'Limpia':'Clean','Contaminada':'Contaminated','Con fístula':'With fistula',
  'Grado 1A · Cierre en 1 paso':'Grade 1A · Closure in 1 step',
  'Sin fijación y cavidad limpia: se puede cerrar de entrada.':'No fixation and a clean cavity: it can be closed straight away.',
  '<b>Paso 1:</b> Cierre primario de la pared y/o reconstrucción de la pared.':'<b>Step 1:</b> Primary wall closure and/or wall reconstruction.',
  'Grado 1B · ABThera® → cierre':'Grade 1B · ABThera® → closure',
  'Sin fijación, cavidad contaminada. Vía SCA (cierre abdominal secuencial).':'No fixation, contaminated cavity. SAC pathway (sequential abdominal closure).',
  '<b>Paso 1:</b> Terapia ABThera® (presión negativa).':'<b>Step 1:</b> ABThera® therapy (negative pressure).',
  '<b>Paso 2:</b> Cierre primario de la pared y/o reconstrucción de la pared.':'<b>Step 2:</b> Primary wall closure and/or wall reconstruction.',
  'Grado 1C · Cirugía → ABThera® → cierre':'Grade 1C · Surgery → ABThera® → closure',
  'Sin fijación, con fístula. La cirugía depende del tipo de fístula.':'No fixation, with fistula. Surgery depends on the type of fistula.',
  '* La conducta quirúrgica depende del tipo de fístula.':'* The surgical approach depends on the type of fistula.',
  '<b>Paso 1:</b> Cirugía* según el tipo de fístula.':'<b>Step 1:</b> Surgery* according to the type of fistula.',
  '<b>Paso 2:</b> Terapia ABThera®.':'<b>Step 2:</b> ABThera® therapy.',
  '<b>Paso 3:</b> Cierre primario de la pared y/o reconstrucción de la pared.':'<b>Step 3:</b> Primary wall closure and/or wall reconstruction.',
  'Grado 2A · Cierre en 1 paso':'Grade 2A · Closure in 1 step',
  'Con adherencia pero cavidad limpia: cierre o reconstrucción de la pared.':'With adherence but a clean cavity: wall closure or reconstruction.',
  'Grado 2B · Terapia V.A.C.® → cierre':'Grade 2B · V.A.C.® therapy → closure',
  'Con adherencia y contaminación: presión negativa antes del cierre.':'With adherence and contamination: negative pressure before closure.',
  '<b>Paso 1:</b> Terapia V.A.C.®':'<b>Step 1:</b> V.A.C.® therapy',
  'Grado 2C · V.A.C.® → cirugía → cierre':'Grade 2C · V.A.C.® → surgery → closure',
  'Con adherencia y fístula.':'With adherence and fistula.',
  '<b>Paso 2:</b> Cirugía* según el tipo de fístula.':'<b>Step 2:</b> Surgery* according to the type of fistula.',
  'Grado 3A · Curaciones → cierre':'Grade 3A · Dressings → closure',
  'Abdomen congelado limpio: no se fuerza el cierre, se maneja con curaciones.':'Clean frozen abdomen: closure is not forced, it is managed with dressings.',
  '<b>Paso 1:</b> Curaciones (dressings).':'<b>Step 1:</b> Dressings.',
  'Grado 3B · Cirugía → curaciones → reconstrucción':'Grade 3B · Surgery → dressings → reconstruction',
  'Abdomen congelado contaminado.':'Contaminated frozen abdomen.',
  '<b>Paso 1:</b> Cirugía.':'<b>Step 1:</b> Surgery.',
  '<b>Paso 2:</b> Curaciones (dressings).':'<b>Step 2:</b> Dressings.',
  '<b>Paso 3:</b> Reconstrucción de la pared.':'<b>Step 3:</b> Wall reconstruction.',
  'Grado 4 · Fístula enteroatmosférica (FEA)':'Grade 4 · Enteroatmospheric fistula (EAF)',
  'El escenario más complejo: manejo dirigido de la fístula.':'The most complex scenario: targeted fistula management.',
  '<b>Paso 2:</b> Cirugía* + manejo de la fístula (aislamiento, dispositivos, control del efluente).':'<b>Step 2:</b> Surgery* + fistula management (isolation, devices, effluent control).',
  '<b>Paso 3:</b> Cierre primario de la pared y/o reconstrucción.':'<b>Step 3:</b> Primary wall closure and/or reconstruction.',

  /* --- Antibióticos --- */
  'Antibióticos en abdomen abierto':'Antibiotics in the open abdomen',
  'Flujograma MIAA — Antibióticos en abdomen abierto (curso MIAA)':'MIAA flowchart — Antibiotics in the open abdomen (MIAA course)',
  '¿El abdomen abierto es inicialmente INFECCIOSO?':'Is the open abdomen initially INFECTIOUS?',
  'Es decir, si el origen del abdomen abierto fue un foco infeccioso (peritonitis, perforación, sepsis abdominal).':'That is, whether the open abdomen originated from an infectious source (peritonitis, perforation, abdominal sepsis).',
  'Sí, infeccioso':'Yes, infectious','No, no infeccioso':'No, not infectious',
  'Bajo antibióticos "profilácticos" y vigilando el posible foco: ¿hay mejoría clínica?':'On “prophylactic” antibiotics while monitoring the possible source: is there clinical improvement?',
  'Sí, mejora':'Yes, improving','No mejora':'Not improving',
  'Revalore el foco infeccioso con estudios. ¿Qué encuentra?':'Reassess the infectious source with imaging/tests. What do you find?',
  'Considere también otros factores de riesgo (por ejemplo, infección por hongos).':'Also consider other risk factors (for example, fungal infection).',
  'Nuevo foco infeccioso extraabdominal':'New extra-abdominal infectious source',
  'Foco infeccioso abdominal no controlado':'Uncontrolled abdominal infectious source',
  'Iniciados los antibióticos empíricos, con control del foco y toma de cultivos, y ajustados según cultivo: ¿hay mejoría clínica?':'With empirical antibiotics started, source control achieved, cultures taken and therapy adjusted to culture: is there clinical improvement?',
  'Mantener la conducta':'Continue current management',
  'Sin foco infeccioso inicial y con mejoría clínica.':'No initial infectious source and clinical improvement.',
  'Antibióticos "profilácticos" con vigilancia del posible foco.':'“Prophylactic” antibiotics with monitoring of the possible source.',
  'Mantener estrategias de abdomen abierto.':'Maintain open abdomen strategies.',
  'Objetivo: Mantener las estrategias de abdomen abierto hasta lograr el CIERRE DEFINITIVO.':'Goal: maintain open abdomen strategies until DEFINITIVE CLOSURE is achieved.',
  'Nuevo foco infeccioso EXTRAABDOMINAL':'New EXTRA-ABDOMINAL infectious source',
  'La falta de mejoría se explica fuera del abdomen: trate ese foco.':'The lack of improvement is explained outside the abdomen: treat that source.',
  'Trate el foco extraabdominal identificado.':'Treat the identified extra-abdominal source.',
  'Considere otros factores de riesgo (p. ej. hongos).':'Consider other risk factors (e.g. fungi).',
  'Mantener estrategias de abdomen abierto hasta el cierre definitivo.':'Maintain open abdomen strategies until definitive closure.',
  'Foco abdominal NO controlado':'Abdominal source NOT controlled',
  'Vuelva al control del foco: reintervención, drenaje y toma de cultivos.':'Return to source control: reoperation, drainage and culture sampling.',
  'Este es el punto crítico del algoritmo: sin control del foco, ningún antibiótico resuelve el cuadro.':'This is the critical point of the algorithm: without source control, no antibiotic will resolve the condition.',
  'Control del foco + toma de cultivos.':'Source control + culture sampling.',
  'Iniciar/ajustar antibióticos según cultivo.':'Start/adjust antibiotics according to culture.',
  'Reevaluar la mejoría clínica.':'Reassess clinical improvement.',
  'Mantener ATB o descalar':'Continue antibiotics or de-escalate',
  'Con foco controlado, cultivos tomados y mejoría clínica: mantener o descalar según criterio clínico.':'With the source controlled, cultures taken and clinical improvement: continue or de-escalate according to clinical judgment.',
  'Mantener o descalar el antibiótico según criterio clínico y cultivos.':'Continue or de-escalate the antibiotic according to clinical judgment and cultures.',
  'Volver al control del foco':'Return to source control',
  'Sin mejoría pese a antibióticos según cultivo: el foco no está controlado.':'No improvement despite culture-guided antibiotics: the source is not controlled.',
  'Sin control del foco, ningún esquema antibiótico resuelve el cuadro.':'Without source control, no antibiotic regimen will resolve the condition.',
  'Reintervención para control del foco + nuevos cultivos.':'Reoperation for source control + new cultures.',
  'Ajustar antibióticos según el nuevo cultivo.':'Adjust antibiotics according to the new culture.',

  /* --- Nutrición --- */
  'Nutrición en abdomen abierto':'Nutrition in the open abdomen',
  'Flujograma MIAA — Nutrición en abdomen abierto (curso MIAA)':'MIAA flowchart — Nutrition in the open abdomen (MIAA course)',
  '¿Funciona el tracto gastrointestinal (TGI)? ¿Puedo usarlo?':'Is the gastrointestinal tract (GIT) working? Can I use it?',
  'Sí, funciona':'Yes, it works','No funciona':'It does not work',
  '→ Nutrición enteral temprana':'→ Early enteral nutrition',
  'Con nutrición enteral temprana: ¿tolera más del 60% de sus requerimientos después de 2 días?':'On early enteral nutrition: does the patient tolerate more than 60% of requirements after 2 days?',
  'Sí, tolera >60%':'Yes, tolerates >60%','No tolera >60%':'Does not tolerate >60%',
  '→ Iniciar NP suplementaria':'→ Start supplemental PN',
  '¿El paciente es capaz de tolerar la vía oral?':'Is the patient able to tolerate the oral route?',
  'Sí':'Yes','No':'No',
  '¿El paciente está desnutrido o en riesgo de desnutrición?':'Is the patient malnourished or at risk of malnutrition?',
  'NRS 2002 ≤3 · NUTRIC ≤5':'NRS 2002 ≤3 · NUTRIC ≤5',
  'Sí, desnutrido o en riesgo':'Yes, malnourished or at risk',
  '¿Hay probabilidad de iniciar nutrición enteral en 3 días?':'Is enteral nutrition likely to be started within 3 days?',
  'Evaluación diaria para iniciar NE':'Daily assessment to start EN',
  '→ Iniciar nutrición parenteral':'→ Start parenteral nutrition',
  '¿Mejoró la función del TGI?':'Has GIT function improved?',
  'Con nutrición parenteral iniciada: ¿mejoró la función del TGI?':'With parenteral nutrition started: has GIT function improved?',
  'Iniciar dieta a tolerancia y suplementos orales':'Start diet as tolerated and oral supplements',
  'El TGI funciona y el paciente tolera la vía oral.':'The GIT works and the patient tolerates the oral route.',
  'Iniciar dieta a tolerancia + suplementos orales.':'Start diet as tolerated + oral supplements.',
  '<b>Proteínas:</b> 1.5–2.5 g/kg/día, <b>+15–30 g adicionales por cada litro de exudado peritoneal</b>.':'<b>Protein:</b> 1.5–2.5 g/kg/day, <b>plus an extra 15–30 g for every litre of peritoneal exudate</b>.',
  '<b>Calorías:</b> 25–30 cal/kg/día.':'<b>Calories:</b> 25–30 cal/kg/day.',
  'Mantener la NP suplementaria iniciada por tolerancia <60%.':'Continue the supplemental PN started because of <60% tolerance.',
  'Continuar nutrición parenteral':'Continue parenteral nutrition',
  'El TGI funciona pero el paciente aún no tolera la vía oral.':'The GIT works but the patient does not yet tolerate the oral route.',
  'Continuar NP mientras no tolere la vía oral.':'Continue PN while the oral route is not tolerated.',
  'Optimizar el soporte nutricional (proteínas, energía y micronutrientes).':'Optimise nutritional support (protein, energy and micronutrients).',
  'Iniciar nutrición enteral temprana':'Start early enteral nutrition',
  'Mejoró la función del TGI: aproveche la vía enteral.':'GIT function improved: take advantage of the enteral route.',
  'Iniciar NE temprana.':'Start early EN.',
  'Reevaluar tolerancia (>60% de requerimientos a los 2 días).':'Reassess tolerance (>60% of requirements at 2 days).',
  'Iniciar NE y destete de la NP':'Start EN and wean off PN',
  'Mejoró la función del TGI con el paciente en parenteral.':'GIT function improved with the patient on parenteral nutrition.',
  'Iniciar nutrición enteral y destetar progresivamente la NP.':'Start enteral nutrition and progressively wean PN.',
  'Optimizar el soporte nutricional':'Optimise nutritional support',
  'El TGI no ha mejorado: asegure aporte suficiente de proteínas, energía y micronutrientes.':'The GIT has not improved: ensure adequate protein, energy and micronutrient intake.',
  'Optimizar el soporte para aportar suficientes proteínas, energía y micronutrientes.':'Optimise support to deliver sufficient protein, energy and micronutrients.',

  /* --- HIA / SCA --- */
  'Manejo de HIA / SCA':'IAH / ACS management',
  'WSACS — IAH/ACS Management Algorithm (Intensive Care Med 2013;7:1190-1206)':'WSACS — IAH/ACS Management Algorithm (Intensive Care Med 2013;7:1190-1206)',
  '¿La presión intraabdominal (PIA) es ≥ 12 mmHg?':'Is the intra-abdominal pressure (IAP) ≥ 12 mmHg?',
  'PIA ≥12 mmHg define hipertensión intraabdominal (HIA).':'IAP ≥12 mmHg defines intra-abdominal hypertension (IAH).',
  'Sí, PIA ≥ 12 mmHg':'Yes, IAP ≥ 12 mmHg','El paciente tiene HIA':'The patient has IAH',
  'No, PIA < 12 mmHg':'No, IAP < 12 mmHg',
  '¿PIA > 20 mmHg CON falla orgánica nueva?':'IAP > 20 mmHg WITH new organ failure?',
  'Esa combinación define síndrome compartimental abdominal (SCA).':'That combination defines abdominal compartment syndrome (ACS).',
  'El paciente tiene SCA':'The patient has ACS',
  '¿Es un SCA primario?':'Is it a primary ACS?',
  'Primario: por lesión o enfermedad de la región abdomino-pélvica. Secundario: de origen extraabdominal. Recurrente: reaparece tras tratamiento previo.':'Primary: from injury or disease of the abdomino-pelvic region. Secondary: of extra-abdominal origin. Recurrent: reappears after previous treatment.',
  'Sí, SCA primario':'Yes, primary ACS','No — secundario o recurrente':'No — secondary or recurrent',
  '¿PIA > 20 mmHg con falla orgánica PROGRESIVA?':'IAP > 20 mmHg with PROGRESSIVE organ failure?',
  'La HIA se ha resuelto':'IAH has resolved',
  'PIA < 12 mmHg de forma consistente.':'IAP consistently < 12 mmHg.',
  'Disminuir la frecuencia de las mediciones de PIA.':'Decrease the frequency of IAP measurements.',
  'Observar al paciente por deterioro clínico.':'Observe the patient for clinical deterioration.',
  'Tratamiento médico para reducir la PIA':'Medical treatment to reduce IAP',
  'Aún no hay indicación de descompresión quirúrgica: escale las medidas médicas.':'There is no indication for surgical decompression yet: escalate medical measures.',
  'Iniciar tratamiento médico para reducir la PIA <i>(Grado 1C)</i>.':'Start medical treatment to reduce IAP <i>(Grade 1C)</i>.',
  '<b>Evitar la reanimación excesiva con fluidos</b> y optimizar la perfusión de órganos.':'<b>Avoid excessive fluid resuscitation</b> and optimise organ perfusion.',
  'Medir la PIA con mediciones seriadas al menos cada 4 h mientras el paciente esté crítico <i>(Grado 1C)</i>.':'Measure IAP with serial measurements at least every 4 h while the patient is critically ill <i>(Grade 1C)</i>.',
  'Reevaluar: si aparece PIA >20 mmHg con falla orgánica nueva, el paciente tiene SCA.':'Reassess: if IAP >20 mmHg with new organ failure appears, the patient has ACS.',
  'Descompresión abdominal quirúrgica':'Surgical abdominal decompression',
  'Identifique y trate la etiología subyacente del SCA.':'Identify and treat the underlying aetiology of the ACS.',
  'Realizar o revisar la descompresión abdominal con cierre temporal según sea necesario para reducir la PIA <i>(Grado 2D)</i>.':'Perform or revise abdominal decompression with temporary closure as needed to reduce IAP <i>(Grade 2D)</i>.',
  'Continuar las medidas médicas para reducir la PIA <i>(Grado 1C)</i>.':'Continue medical measures to reduce IAP <i>(Grade 1C)</i>.',
  'Medir la PIA al menos cada 4 h mientras el paciente esté crítico <i>(Grado 1C)</i>.':'Measure IAP at least every 4 h while the patient is critically ill <i>(Grade 1C)</i>.',
  'Reanimación balanceada de precarga, contractilidad y poscarga — <b>evitar la reanimación excesiva con fluidos</b> <i>(Grado 2D)</i>.':'Balanced resuscitation of preload, contractility and afterload — <b>avoid excessive fluid resuscitation</b> <i>(Grade 2D)</i>.'
},
pt: {
  'Referencia':'Referência',
  /* --- Conduta segundo o grau de Björck --- */
  'Conducta según grado de Björck':'Conduta segundo o grau de Björck',
  'Flujograma MIAA — Conducta según grado de Björck (curso MIAA)':'Fluxograma MIAA — Conduta segundo o grau de Björck (curso MIAA)',
  '¿Hay adherencia o fijación de las vísceras a la pared?':'Há aderência ou fixação das vísceras à parede?',
  'Define la vía: sin fijación (grados 1) permite cierre precoz; con fijación (grados 2) exige terapia de presión negativa primero.':'Define o caminho: sem fixação (grau 1) permite fechamento precoce; com fixação (grau 2) exige terapia de pressão negativa primeiro.',
  'No — sin adherencia ni fijación':'Não — sem aderência nem fixação',
  'Sí — con adherencia o fijación':'Sim — com aderência ou fixação',
  'Abdomen congelado (frozen)':'Abdome congelado (frozen)',
  'Fístula enteroatmosférica (FEA)':'Fístula enteroatmosférica (FEA)',
  'Grado 1':'Grau 1','Grado 2':'Grau 2','Grado 3':'Grau 3','Grado 4':'Grau 4',
  '¿En qué estado está la cavidad?':'Em que estado está a cavidade?',
  'Limpia':'Limpa','Contaminada':'Contaminada','Con fístula':'Com fístula',
  'Grado 1A · Cierre en 1 paso':'Grau 1A · Fechamento em 1 passo',
  'Sin fijación y cavidad limpia: se puede cerrar de entrada.':'Sem fixação e cavidade limpa: pode ser fechado de imediato.',
  '<b>Paso 1:</b> Cierre primario de la pared y/o reconstrucción de la pared.':'<b>Passo 1:</b> Fechamento primário da parede e/ou reconstrução da parede.',
  'Grado 1B · ABThera® → cierre':'Grau 1B · ABThera® → fechamento',
  'Sin fijación, cavidad contaminada. Vía SCA (cierre abdominal secuencial).':'Sem fixação, cavidade contaminada. Via FAS (fechamento abdominal sequencial).',
  '<b>Paso 1:</b> Terapia ABThera® (presión negativa).':'<b>Passo 1:</b> Terapia ABThera® (pressão negativa).',
  '<b>Paso 2:</b> Cierre primario de la pared y/o reconstrucción de la pared.':'<b>Passo 2:</b> Fechamento primário da parede e/ou reconstrução da parede.',
  'Grado 1C · Cirugía → ABThera® → cierre':'Grau 1C · Cirurgia → ABThera® → fechamento',
  'Sin fijación, con fístula. La cirugía depende del tipo de fístula.':'Sem fixação, com fístula. A cirurgia depende do tipo de fístula.',
  '* La conducta quirúrgica depende del tipo de fístula.':'* A conduta cirúrgica depende do tipo de fístula.',
  '<b>Paso 1:</b> Cirugía* según el tipo de fístula.':'<b>Passo 1:</b> Cirurgia* conforme o tipo de fístula.',
  '<b>Paso 2:</b> Terapia ABThera®.':'<b>Passo 2:</b> Terapia ABThera®.',
  '<b>Paso 3:</b> Cierre primario de la pared y/o reconstrucción de la pared.':'<b>Passo 3:</b> Fechamento primário da parede e/ou reconstrução da parede.',
  'Grado 2A · Cierre en 1 paso':'Grau 2A · Fechamento em 1 passo',
  'Con adherencia pero cavidad limpia: cierre o reconstrucción de la pared.':'Com aderência mas cavidade limpa: fechamento ou reconstrução da parede.',
  'Grado 2B · Terapia V.A.C.® → cierre':'Grau 2B · Terapia V.A.C.® → fechamento',
  'Con adherencia y contaminación: presión negativa antes del cierre.':'Com aderência e contaminação: pressão negativa antes do fechamento.',
  '<b>Paso 1:</b> Terapia V.A.C.®':'<b>Passo 1:</b> Terapia V.A.C.®',
  'Grado 2C · V.A.C.® → cirugía → cierre':'Grau 2C · V.A.C.® → cirurgia → fechamento',
  'Con adherencia y fístula.':'Com aderência e fístula.',
  '<b>Paso 2:</b> Cirugía* según el tipo de fístula.':'<b>Passo 2:</b> Cirurgia* conforme o tipo de fístula.',
  'Grado 3A · Curaciones → cierre':'Grau 3A · Curativos → fechamento',
  'Abdomen congelado limpio: no se fuerza el cierre, se maneja con curaciones.':'Abdome congelado limpo: não se força o fechamento, maneja-se com curativos.',
  '<b>Paso 1:</b> Curaciones (dressings).':'<b>Passo 1:</b> Curativos.',
  'Grado 3B · Cirugía → curaciones → reconstrucción':'Grau 3B · Cirurgia → curativos → reconstrução',
  'Abdomen congelado contaminado.':'Abdome congelado contaminado.',
  '<b>Paso 1:</b> Cirugía.':'<b>Passo 1:</b> Cirurgia.',
  '<b>Paso 2:</b> Curaciones (dressings).':'<b>Passo 2:</b> Curativos.',
  '<b>Paso 3:</b> Reconstrucción de la pared.':'<b>Passo 3:</b> Reconstrução da parede.',
  'Grado 4 · Fístula enteroatmosférica (FEA)':'Grau 4 · Fístula enteroatmosférica (FEA)',
  'El escenario más complejo: manejo dirigido de la fístula.':'O cenário mais complexo: manejo dirigido da fístula.',
  '<b>Paso 2:</b> Cirugía* + manejo de la fístula (aislamiento, dispositivos, control del efluente).':'<b>Passo 2:</b> Cirurgia* + manejo da fístula (isolamento, dispositivos, controle do efluente).',
  '<b>Paso 3:</b> Cierre primario de la pared y/o reconstrucción.':'<b>Passo 3:</b> Fechamento primário da parede e/ou reconstrução.',

  /* --- Antibióticos --- */
  'Antibióticos en abdomen abierto':'Antibióticos no abdome aberto',
  'Flujograma MIAA — Antibióticos en abdomen abierto (curso MIAA)':'Fluxograma MIAA — Antibióticos no abdome aberto (curso MIAA)',
  '¿El abdomen abierto es inicialmente INFECCIOSO?':'O abdome aberto é inicialmente INFECCIOSO?',
  'Es decir, si el origen del abdomen abierto fue un foco infeccioso (peritonitis, perforación, sepsis abdominal).':'Ou seja, se a origem do abdome aberto foi um foco infeccioso (peritonite, perfuração, sepse abdominal).',
  'Sí, infeccioso':'Sim, infeccioso','No, no infeccioso':'Não, não infeccioso',
  'Bajo antibióticos "profilácticos" y vigilando el posible foco: ¿hay mejoría clínica?':'Sob antibióticos “profiláticos” e vigiando o possível foco: há melhora clínica?',
  'Sí, mejora':'Sim, melhora','No mejora':'Não melhora',
  'Revalore el foco infeccioso con estudios. ¿Qué encuentra?':'Reavalie o foco infeccioso com exames. O que encontra?',
  'Considere también otros factores de riesgo (por ejemplo, infección por hongos).':'Considere também outros fatores de risco (por exemplo, infecção fúngica).',
  'Nuevo foco infeccioso extraabdominal':'Novo foco infeccioso extra-abdominal',
  'Foco infeccioso abdominal no controlado':'Foco infeccioso abdominal não controlado',
  'Iniciados los antibióticos empíricos, con control del foco y toma de cultivos, y ajustados según cultivo: ¿hay mejoría clínica?':'Iniciados os antibióticos empíricos, com controle do foco e coleta de culturas, e ajustados conforme a cultura: há melhora clínica?',
  'Mantener la conducta':'Manter a conduta',
  'Sin foco infeccioso inicial y con mejoría clínica.':'Sem foco infeccioso inicial e com melhora clínica.',
  'Antibióticos "profilácticos" con vigilancia del posible foco.':'Antibióticos “profiláticos” com vigilância do possível foco.',
  'Mantener estrategias de abdomen abierto.':'Manter as estratégias de abdome aberto.',
  'Objetivo: Mantener las estrategias de abdomen abierto hasta lograr el CIERRE DEFINITIVO.':'Objetivo: manter as estratégias de abdome aberto até alcançar o FECHAMENTO DEFINITIVO.',
  'Nuevo foco infeccioso EXTRAABDOMINAL':'Novo foco infeccioso EXTRA-ABDOMINAL',
  'La falta de mejoría se explica fuera del abdomen: trate ese foco.':'A falta de melhora se explica fora do abdome: trate esse foco.',
  'Trate el foco extraabdominal identificado.':'Trate o foco extra-abdominal identificado.',
  'Considere otros factores de riesgo (p. ej. hongos).':'Considere outros fatores de risco (p. ex. fungos).',
  'Mantener estrategias de abdomen abierto hasta el cierre definitivo.':'Manter as estratégias de abdome aberto até o fechamento definitivo.',
  'Foco abdominal NO controlado':'Foco abdominal NÃO controlado',
  'Vuelva al control del foco: reintervención, drenaje y toma de cultivos.':'Volte ao controle do foco: reintervenção, drenagem e coleta de culturas.',
  'Este es el punto crítico del algoritmo: sin control del foco, ningún antibiótico resuelve el cuadro.':'Este é o ponto crítico do algoritmo: sem controle do foco, nenhum antibiótico resolve o quadro.',
  'Control del foco + toma de cultivos.':'Controle do foco + coleta de culturas.',
  'Iniciar/ajustar antibióticos según cultivo.':'Iniciar/ajustar antibióticos conforme a cultura.',
  'Reevaluar la mejoría clínica.':'Reavaliar a melhora clínica.',
  'Mantener ATB o descalar':'Manter ATB ou descalonar',
  'Con foco controlado, cultivos tomados y mejoría clínica: mantener o descalar según criterio clínico.':'Com foco controlado, culturas coletadas e melhora clínica: manter ou descalonar conforme critério clínico.',
  'Mantener o descalar el antibiótico según criterio clínico y cultivos.':'Manter ou descalonar o antibiótico conforme critério clínico e culturas.',
  'Volver al control del foco':'Voltar ao controle do foco',
  'Sin mejoría pese a antibióticos según cultivo: el foco no está controlado.':'Sem melhora apesar dos antibióticos conforme cultura: o foco não está controlado.',
  'Sin control del foco, ningún esquema antibiótico resuelve el cuadro.':'Sem controle do foco, nenhum esquema antibiótico resolve o quadro.',
  'Reintervención para control del foco + nuevos cultivos.':'Reintervenção para controle do foco + novas culturas.',
  'Ajustar antibióticos según el nuevo cultivo.':'Ajustar antibióticos conforme a nova cultura.',

  /* --- Nutrição --- */
  'Nutrición en abdomen abierto':'Nutrição no abdome aberto',
  'Flujograma MIAA — Nutrición en abdomen abierto (curso MIAA)':'Fluxograma MIAA — Nutrição no abdome aberto (curso MIAA)',
  '¿Funciona el tracto gastrointestinal (TGI)? ¿Puedo usarlo?':'O trato gastrointestinal (TGI) funciona? Posso usá-lo?',
  'Sí, funciona':'Sim, funciona','No funciona':'Não funciona',
  '→ Nutrición enteral temprana':'→ Nutrição enteral precoce',
  'Con nutrición enteral temprana: ¿tolera más del 60% de sus requerimientos después de 2 días?':'Com nutrição enteral precoce: tolera mais de 60% das suas necessidades após 2 dias?',
  'Sí, tolera >60%':'Sim, tolera >60%','No tolera >60%':'Não tolera >60%',
  '→ Iniciar NP suplementaria':'→ Iniciar NP suplementar',
  '¿El paciente es capaz de tolerar la vía oral?':'O paciente é capaz de tolerar a via oral?',
  'Sí':'Sim','No':'Não',
  '¿El paciente está desnutrido o en riesgo de desnutrición?':'O paciente está desnutrido ou em risco de desnutrição?',
  'NRS 2002 ≤3 · NUTRIC ≤5':'NRS 2002 ≤3 · NUTRIC ≤5',
  'Sí, desnutrido o en riesgo':'Sim, desnutrido ou em risco',
  '¿Hay probabilidad de iniciar nutrición enteral en 3 días?':'Há probabilidade de iniciar nutrição enteral em 3 dias?',
  'Evaluación diaria para iniciar NE':'Avaliação diária para iniciar NE',
  '→ Iniciar nutrición parenteral':'→ Iniciar nutrição parenteral',
  '¿Mejoró la función del TGI?':'A função do TGI melhorou?',
  'Con nutrición parenteral iniciada: ¿mejoró la función del TGI?':'Com nutrição parenteral iniciada: a função do TGI melhorou?',
  'Iniciar dieta a tolerancia y suplementos orales':'Iniciar dieta conforme tolerância e suplementos orais',
  'El TGI funciona y el paciente tolera la vía oral.':'O TGI funciona e o paciente tolera a via oral.',
  'Iniciar dieta a tolerancia + suplementos orales.':'Iniciar dieta conforme tolerância + suplementos orais.',
  '<b>Proteínas:</b> 1.5–2.5 g/kg/día, <b>+15–30 g adicionales por cada litro de exudado peritoneal</b>.':'<b>Proteínas:</b> 1,5–2,5 g/kg/dia, <b>+15–30 g adicionais por cada litro de exsudato peritoneal</b>.',
  '<b>Calorías:</b> 25–30 cal/kg/día.':'<b>Calorias:</b> 25–30 cal/kg/dia.',
  'Mantener la NP suplementaria iniciada por tolerancia <60%.':'Manter a NP suplementar iniciada por tolerância <60%.',
  'Continuar nutrición parenteral':'Continuar nutrição parenteral',
  'El TGI funciona pero el paciente aún no tolera la vía oral.':'O TGI funciona, mas o paciente ainda não tolera a via oral.',
  'Continuar NP mientras no tolere la vía oral.':'Continuar NP enquanto não tolerar a via oral.',
  'Optimizar el soporte nutricional (proteínas, energía y micronutrientes).':'Otimizar o suporte nutricional (proteínas, energia e micronutrientes).',
  'Iniciar nutrición enteral temprana':'Iniciar nutrição enteral precoce',
  'Mejoró la función del TGI: aproveche la vía enteral.':'A função do TGI melhorou: aproveite a via enteral.',
  'Iniciar NE temprana.':'Iniciar NE precoce.',
  'Reevaluar tolerancia (>60% de requerimientos a los 2 días).':'Reavaliar a tolerância (>60% das necessidades em 2 dias).',
  'Iniciar NE y destete de la NP':'Iniciar NE e desmame da NP',
  'Mejoró la función del TGI con el paciente en parenteral.':'A função do TGI melhorou com o paciente em parenteral.',
  'Iniciar nutrición enteral y destetar progresivamente la NP.':'Iniciar nutrição enteral e desmamar progressivamente a NP.',
  'Optimizar el soporte nutricional':'Otimizar o suporte nutricional',
  'El TGI no ha mejorado: asegure aporte suficiente de proteínas, energía y micronutrientes.':'O TGI não melhorou: assegure aporte suficiente de proteínas, energia e micronutrientes.',
  'Optimizar el soporte para aportar suficientes proteínas, energía y micronutrientes.':'Otimizar o suporte para fornecer proteínas, energia e micronutrientes suficientes.',

  /* --- HIA / SCA --- */
  'Manejo de HIA / SCA':'Manejo de HIA / SCA',
  'WSACS — IAH/ACS Management Algorithm (Intensive Care Med 2013;7:1190-1206)':'WSACS — IAH/ACS Management Algorithm (Intensive Care Med 2013;7:1190-1206)',
  '¿La presión intraabdominal (PIA) es ≥ 12 mmHg?':'A pressão intra-abdominal (PIA) é ≥ 12 mmHg?',
  'PIA ≥12 mmHg define hipertensión intraabdominal (HIA).':'PIA ≥12 mmHg define hipertensão intra-abdominal (HIA).',
  'Sí, PIA ≥ 12 mmHg':'Sim, PIA ≥ 12 mmHg','El paciente tiene HIA':'O paciente tem HIA',
  'No, PIA < 12 mmHg':'Não, PIA < 12 mmHg',
  '¿PIA > 20 mmHg CON falla orgánica nueva?':'PIA > 20 mmHg COM falência orgânica nova?',
  'Esa combinación define síndrome compartimental abdominal (SCA).':'Essa combinação define síndrome compartimental abdominal (SCA).',
  'El paciente tiene SCA':'O paciente tem SCA',
  '¿Es un SCA primario?':'É um SCA primário?',
  'Primario: por lesión o enfermedad de la región abdomino-pélvica. Secundario: de origen extraabdominal. Recurrente: reaparece tras tratamiento previo.':'Primário: por lesão ou doença da região abdomino-pélvica. Secundário: de origem extra-abdominal. Recorrente: reaparece após tratamento prévio.',
  'Sí, SCA primario':'Sim, SCA primário','No — secundario o recurrente':'Não — secundário ou recorrente',
  '¿PIA > 20 mmHg con falla orgánica PROGRESIVA?':'PIA > 20 mmHg com falência orgânica PROGRESSIVA?',
  'La HIA se ha resuelto':'A HIA foi resolvida',
  'PIA < 12 mmHg de forma consistente.':'PIA < 12 mmHg de forma consistente.',
  'Disminuir la frecuencia de las mediciones de PIA.':'Diminuir a frequência das medições de PIA.',
  'Observar al paciente por deterioro clínico.':'Observar o paciente quanto a deterioração clínica.',
  'Tratamiento médico para reducir la PIA':'Tratamento clínico para reduzir a PIA',
  'Aún no hay indicación de descompresión quirúrgica: escale las medidas médicas.':'Ainda não há indicação de descompressão cirúrgica: escalone as medidas clínicas.',
  'Iniciar tratamiento médico para reducir la PIA <i>(Grado 1C)</i>.':'Iniciar tratamento clínico para reduzir a PIA <i>(Grau 1C)</i>.',
  '<b>Evitar la reanimación excesiva con fluidos</b> y optimizar la perfusión de órganos.':'<b>Evitar a reanimação excessiva com fluidos</b> e otimizar a perfusão dos órgãos.',
  'Medir la PIA con mediciones seriadas al menos cada 4 h mientras el paciente esté crítico <i>(Grado 1C)</i>.':'Medir a PIA com medições seriadas pelo menos a cada 4 h enquanto o paciente estiver crítico <i>(Grau 1C)</i>.',
  'Reevaluar: si aparece PIA >20 mmHg con falla orgánica nueva, el paciente tiene SCA.':'Reavaliar: se surgir PIA >20 mmHg com falência orgânica nova, o paciente tem SCA.',
  'Descompresión abdominal quirúrgica':'Descompressão abdominal cirúrgica',
  'Identifique y trate la etiología subyacente del SCA.':'Identifique e trate a etiologia subjacente do SCA.',
  'Realizar o revisar la descompresión abdominal con cierre temporal según sea necesario para reducir la PIA <i>(Grado 2D)</i>.':'Realizar ou revisar a descompressão abdominal com fechamento temporário conforme necessário para reduzir a PIA <i>(Grau 2D)</i>.',
  'Continuar las medidas médicas para reducir la PIA <i>(Grado 1C)</i>.':'Continuar as medidas clínicas para reduzir a PIA <i>(Grau 1C)</i>.',
  'Medir la PIA al menos cada 4 h mientras el paciente esté crítico <i>(Grado 1C)</i>.':'Medir a PIA pelo menos a cada 4 h enquanto o paciente estiver crítico <i>(Grau 1C)</i>.',
  'Reanimación balanceada de precarga, contractilidad y poscarga — <b>evitar la reanimación excesiva con fluidos</b> <i>(Grado 2D)</i>.':'Reanimação balanceada de pré-carga, contratilidade e pós-carga — <b>evitar a reanimação excessiva com fluidos</b> <i>(Grau 2D)</i>.'
}
};
