/* ============================================================
   MIP — Traducciones EN/PT
   Mapeadas por el texto ES canónico que vive en index.html
   (mismo patrón que aast/aast-trans.js).
   Si una clave no existe, se muestra el español tal cual.
   ============================================================ */
window.MIP_TRANS = {
en: {
  /* --- UI --- */
  'Herramientas Clínicas':'Clinical Tools',
  'MIP — Manejo Integral del Politraumatizado':'MIP — Comprehensive Polytrauma Management',
  'MIP — Manejo Integral del Politraumatizado · EduTrauma':'MIP — Comprehensive Polytrauma Management · EduTrauma',
  'Algoritmos de decisión del abordaje primario (ABCDE). Toca un algoritmo.':'Decision algorithms for the primary survey (ABCDE). Tap an algorithm.',
  'Buscar algoritmo…':'Search algorithm…',
  '★ Recientes':'★ Recent',
  'Sin resultados':'No results',
  'Ver todas las herramientas ›':'See all tools ›',
  'Danos tu opinión':'Give us feedback',
  '‹ Atrás':'‹ Back',
  '‹ Todos los algoritmos':'‹ All algorithms',
  'Ver resultado ›':'See result ›',
  'Referencia':'Reference',
  'Otro algoritmo':'Another algorithm',
  '¿Cuál es tu especialidad?':'What is your specialty?',
  'Un toque, solo una vez — nos ayuda a crear las herramientas que tu práctica necesita.':'One tap, just once — it helps us build the tools your practice needs.',
  'Cirugía general':'General surgery','Cirugía de trauma':'Trauma surgery','Residente de cirugía':'Surgery resident',
  'Medicina de urgencia':'Emergency medicine','Enfermería':'Nursing','Estudiante de medicina':'Medical student','Otra':'Other',
  'Escríbela aquí… (ej: Veterinaria)':'Type it here… (e.g. Veterinary)','Continuar ›':'Continue ›',
  'Instala esta app en tu pantalla de inicio, incluso sin conexión.':'Install this app on your home screen, even offline.',
  'Instalar':'Install',
  'Guárdala en tu pantalla de inicio — funciona sin conexión.':'Save it to your home screen — works offline.',
  '¿Cómo?':'How?','Instalar en tu iPhone':'Install on your iPhone','Entendido':'Got it',
  'Toca el botón <b>Compartir</b> (el cuadrado con flecha ↑) en Safari':'Tap the <b>Share</b> button (the square with an ↑ arrow) in Safari',
  'Elige <b>“Agregar a pantalla de inicio”</b>':'Choose <b>“Add to Home Screen”</b>',
  'Toca <b>Agregar</b>':'Tap <b>Add</b>',
  'Herramienta de apoyo a la decisión clínica — no reemplaza el juicio médico.<br>EduTrauma® — Enseñando a salvar vidas.<br><span style="opacity:0.75">© 2026 EduTrauma® · Todos los derechos reservados. Prohibida su comercialización, reproducción o modificación sin autorización escrita.</span>':
    'Clinical decision support tool — it does not replace medical judgment.<br>EduTrauma® — Teaching to save lives.<br><span style="opacity:0.75">© 2026 EduTrauma® · All rights reserved. Commercialization, reproduction or modification without written authorization is prohibited.</span>',

  /* --- Regiones --- */
  'Vía aérea (A)':'Airway (A)',
  'Control de columna cervical (A)':'Cervical spine control (A)',

  /* --- Restricción del movimiento espinal --- */
  'Restricción del movimiento espinal':'Spinal motion restriction',
  'Collarín cervical: colocar, mantener o retirar según el mecanismo.':'Cervical collar: apply, keep or remove according to the mechanism.',
  'Algoritmo MIP — Restricción del movimiento espinal (Dr. Pablo Ottolino, curso MIP, 2026)':'MIP algorithm — Spinal motion restriction (Dr. Pablo Ottolino, MIP course, 2026)',
  '¿Cuál fue el mecanismo de trauma?':'What was the mechanism of injury?',
  'Penetrante':'Penetrating','Arma blanca, proyectil':'Stab wound, gunshot',
  'Cerrado (contuso)':'Blunt','Caída, colisión, aplastamiento':'Fall, collision, crush',
  '¿El paciente YA trae el collarín puesto?':'Is the patient ALREADY wearing a collar?',
  'De esto depende si la conducta se enuncia como «colocar / mantener» o como «retirar / no colocar». La lógica es la misma.':'This determines whether the action reads as “apply / keep” or as “remove / do not apply”. The logic is the same.',
  'Sí, ya lo trae':'Yes, already wearing it','No lo trae':'Not wearing it',
  '¿Dónde está la herida penetrante?':'Where is the penetrating wound?',
  'Cuello':'Neck','Cráneo / Torso / Extremidades':'Skull / Torso / Extremities',
  'Abra la parte frontal del collarín y examine la herida. ¿Hay signos de lesión medular?':'Open the front of the collar and examine the wound. Are there signs of spinal cord injury?',
  'Déficit motor o sensitivo, o dolor/deformidad en la línea media cervical.':'Motor or sensory deficit, or midline cervical pain/deformity.',
  'Sí, hay lesión medular':'Yes, spinal cord injury','No hay lesión medular':'No spinal cord injury',
  'Mantener el collarín':'Keep the collar',
  'Mecanismo cerrado: dedíquese a las lesiones potencialmente mortales y espere a la evaluación secundaria.':'Blunt mechanism: focus on life-threatening injuries and wait for the secondary survey.',
  'Pendiente para la 2ª valoración: aplique los criterios NEXUS para decidir si la columna puede liberarse.':'Pending for the secondary survey: apply the NEXUS criteria to decide whether the spine can be cleared.',
  'Aplicar criterios NEXUS ›':'Apply NEXUS criteria ›',
  'Herida penetrante en cuello con signos de lesión medular: la columna debe permanecer inmovilizada.':'Penetrating neck wound with signs of spinal cord injury: the spine must remain immobilised.',
  'Colocar el collarín':'Apply the collar',
  'Herida penetrante en cuello con signos de lesión medular: inmovilice la columna cervical.':'Penetrating neck wound with signs of spinal cord injury: immobilise the cervical spine.',
  'Retirar el collarín':'Remove the collar',
  'Sin indicación de inmovilización por este mecanismo: el collarín puede retirarse.':'No indication for immobilisation with this mechanism: the collar can be removed.',
  'No colocar el collarín':'Do not apply the collar',
  'Sin indicación de inmovilización por este mecanismo: no es necesario colocar collarín.':'No indication for immobilisation with this mechanism: a collar is not required.',

  /* --- NEXUS --- */
  'Criterios NEXUS':'NEXUS criteria',
  '¿Se puede liberar la columna cervical? 5 criterios.':'Can the cervical spine be cleared? 5 criteria.',
  'NEXUS — Hoffman et al., NEJM 2000 · valoración secundaria, curso MIP':'NEXUS — Hoffman et al., NEJM 2000 · secondary survey, MIP course',
  'Marque los criterios PRESENTES en el paciente. La columna solo se libera si NINGUNO está presente.':'Check the criteria PRESENT in the patient. The spine is cleared only if NONE is present.',
  'Dolor en la línea media cervical':'Midline cervical tenderness',
  'Déficit neurológico focal':'Focal neurological deficit',
  'Estado de alerta anormal (GCS < 14)':'Altered level of alertness (GCS < 14)',
  'Intoxicación':'Intoxication',
  'Lesión distractora':'Distracting injury',
  'Mantener / colocar la inmovilización cervical':'Keep / apply cervical immobilisation',
  '{n} de 5 criterios presentes. Con al menos uno positivo, la columna NO puede liberarse; mantenga la inmovilización.':'{n} of 5 criteria present. With at least one positive, the spine can NOT be cleared; maintain immobilisation.',
  'Se puede liberar el collarín':'The collar can be removed',
  '0 de 5 criterios presentes: ningún criterio positivo, la columna cervical puede liberarse.':'0 of 5 criteria present: no positive criteria, the cervical spine can be cleared.',

  /* --- Vía aérea --- */
  'Evaluación de vía aérea (respuesta verbal)':'Airway assessment (verbal response)',
  'Permeable, obstruida o en riesgo, según la respuesta verbal.':'Patent, obstructed or at risk, based on the verbal response.',
  'Algoritmo MIP — Evaluación 1, Secuencia de Respuesta Verbal (curso MIP, 2026)':'MIP algorithm — Assessment 1, Verbal Response Sequence (MIP course, 2026)',
  '¿El paciente emite respuesta verbal?':'Does the patient give a verbal response?',
  'Sí, responde':'Yes, responds','No responde':'No response',
  'Calidad de la respuesta:':'Quality of the response:',
  'Coherente':'Coherent','Incoherente':'Incoherent',
  'Características de la voz: ¿hay alteración?':'Voice characteristics: is there any alteration?',
  'Disfonía, estridor, voz «apagada» o gorgoteo sugieren lesión de la vía aérea.':'Hoarseness, stridor, a muffled voice or gurgling suggest airway injury.',
  'Sí, voz alterada':'Yes, altered voice','No, voz normal':'No, normal voice',
  '¿Hay compromiso neurológico?':'Is there neurological compromise?',
  'Sí':'Yes','No':'No',
  '¿Hay obstrucción mecánica de la vía aérea?':'Is there mechanical airway obstruction?',
  'Cuerpo extraño, sangre, secreciones, edema o compresión.':'Foreign body, blood, secretions, oedema or compression.',
  'Vía aérea permeable':'Patent airway',
  'La vía aérea está permeable en este momento. Continúe con el abordaje primario (B).':'The airway is patent at this time. Continue with the primary survey (B).',
  'Vía aérea permeable, pero LESIONADA':'Airway patent, but INJURED',
  'Permeable ahora, pero con signos de lesión.':'Patent now, but with signs of injury.',
  '⚠ Puede evolucionar a obstrucción de la vía aérea asociada a la lesión. REEVALÚE de forma periódica durante la reanimación.':'⚠ It may progress to airway obstruction associated with the injury. REASSESS periodically during resuscitation.',
  '¡PROTEGER LA VÍA AÉREA!':'PROTECT THE AIRWAY!',
  'Respuesta incoherente con compromiso neurológico: la vía aérea está en riesgo. Asegúrela de inmediato.':'Incoherent response with neurological compromise: the airway is at risk. Secure it immediately.',
  'Vía aérea OBSTRUIDA':'OBSTRUCTED airway',
  'Obstrucción mecánica presente: intervención inmediata de la vía aérea.':'Mechanical obstruction present: immediate airway intervention.',
  'Sin resultado':'No result','Revise las respuestas.':'Review the answers.'
},
pt: {
  /* --- UI --- */
  'Herramientas Clínicas':'Ferramentas Clínicas',
  'MIP — Manejo Integral del Politraumatizado':'MIP — Manejo Integral do Politraumatizado',
  'MIP — Manejo Integral del Politraumatizado · EduTrauma':'MIP — Manejo Integral do Politraumatizado · EduTrauma',
  'Algoritmos de decisión del abordaje primario (ABCDE). Toca un algoritmo.':'Algoritmos de decisão da abordagem primária (ABCDE). Toque em um algoritmo.',
  'Buscar algoritmo…':'Buscar algoritmo…',
  '★ Recientes':'★ Recentes',
  'Sin resultados':'Sem resultados',
  'Ver todas las herramientas ›':'Ver todas as ferramentas ›',
  'Danos tu opinión':'Dê sua opinião',
  '‹ Atrás':'‹ Voltar',
  '‹ Todos los algoritmos':'‹ Todos os algoritmos',
  'Ver resultado ›':'Ver resultado ›',
  'Referencia':'Referência',
  'Otro algoritmo':'Outro algoritmo',
  '¿Cuál es tu especialidad?':'Qual é a sua especialidade?',
  'Un toque, solo una vez — nos ayuda a crear las herramientas que tu práctica necesita.':'Um toque, só uma vez — nos ajuda a criar as ferramentas que a sua prática precisa.',
  'Cirugía general':'Cirurgia geral','Cirugía de trauma':'Cirurgia do trauma','Residente de cirugía':'Residente de cirurgia',
  'Medicina de urgencia':'Medicina de emergência','Enfermería':'Enfermagem','Estudiante de medicina':'Estudante de medicina','Otra':'Outra',
  'Escríbela aquí… (ej: Veterinaria)':'Escreva aqui… (ex.: Veterinária)','Continuar ›':'Continuar ›',
  'Instala esta app en tu pantalla de inicio, incluso sin conexión.':'Instale este app na sua tela de início, mesmo sem conexão.',
  'Instalar':'Instalar',
  'Guárdala en tu pantalla de inicio — funciona sin conexión.':'Salve na sua tela de início — funciona sem conexão.',
  '¿Cómo?':'Como?','Instalar en tu iPhone':'Instalar no seu iPhone','Entendido':'Entendido',
  'Toca el botón <b>Compartir</b> (el cuadrado con flecha ↑) en Safari':'Toque no botão <b>Compartilhar</b> (o quadrado com seta ↑) no Safari',
  'Elige <b>“Agregar a pantalla de inicio”</b>':'Escolha <b>“Adicionar à Tela de Início”</b>',
  'Toca <b>Agregar</b>':'Toque em <b>Adicionar</b>',
  'Herramienta de apoyo a la decisión clínica — no reemplaza el juicio médico.<br>EduTrauma® — Enseñando a salvar vidas.<br><span style="opacity:0.75">© 2026 EduTrauma® · Todos los derechos reservados. Prohibida su comercialización, reproducción o modificación sin autorización escrita.</span>':
    'Ferramenta de apoio à decisão clínica — não substitui o julgamento médico.<br>EduTrauma® — Ensinando a salvar vidas.<br><span style="opacity:0.75">© 2026 EduTrauma® · Todos os direitos reservados. Proibida a comercialização, reprodução ou modificação sem autorização por escrito.</span>',

  /* --- Regiões --- */
  'Vía aérea (A)':'Via aérea (A)',
  'Control de columna cervical (A)':'Controle da coluna cervical (A)',

  /* --- Restrição do movimento espinhal --- */
  'Restricción del movimiento espinal':'Restrição do movimento espinhal',
  'Collarín cervical: colocar, mantener o retirar según el mecanismo.':'Colar cervical: colocar, manter ou retirar conforme o mecanismo.',
  'Algoritmo MIP — Restricción del movimiento espinal (Dr. Pablo Ottolino, curso MIP, 2026)':'Algoritmo MIP — Restrição do movimento espinhal (Dr. Pablo Ottolino, curso MIP, 2026)',
  '¿Cuál fue el mecanismo de trauma?':'Qual foi o mecanismo de trauma?',
  'Penetrante':'Penetrante','Arma blanca, proyectil':'Arma branca, projétil',
  'Cerrado (contuso)':'Fechado (contuso)','Caída, colisión, aplastamiento':'Queda, colisão, esmagamento',
  '¿El paciente YA trae el collarín puesto?':'O paciente JÁ está com o colar cervical?',
  'De esto depende si la conducta se enuncia como «colocar / mantener» o como «retirar / no colocar». La lógica es la misma.':'Disso depende se a conduta é enunciada como «colocar / manter» ou como «retirar / não colocar». A lógica é a mesma.',
  'Sí, ya lo trae':'Sim, já está com ele','No lo trae':'Não está com ele',
  '¿Dónde está la herida penetrante?':'Onde está a ferida penetrante?',
  'Cuello':'Pescoço','Cráneo / Torso / Extremidades':'Crânio / Tronco / Extremidades',
  'Abra la parte frontal del collarín y examine la herida. ¿Hay signos de lesión medular?':'Abra a parte frontal do colar e examine a ferida. Há sinais de lesão medular?',
  'Déficit motor o sensitivo, o dolor/deformidad en la línea media cervical.':'Déficit motor ou sensitivo, ou dor/deformidade na linha média cervical.',
  'Sí, hay lesión medular':'Sim, há lesão medular','No hay lesión medular':'Não há lesão medular',
  'Mantener el collarín':'Manter o colar',
  'Mecanismo cerrado: dedíquese a las lesiones potencialmente mortales y espere a la evaluación secundaria.':'Mecanismo fechado: dedique-se às lesões potencialmente fatais e aguarde a avaliação secundária.',
  'Pendiente para la 2ª valoración: aplique los criterios NEXUS para decidir si la columna puede liberarse.':'Pendente para a 2ª avaliação: aplique os critérios NEXUS para decidir se a coluna pode ser liberada.',
  'Aplicar criterios NEXUS ›':'Aplicar critérios NEXUS ›',
  'Herida penetrante en cuello con signos de lesión medular: la columna debe permanecer inmovilizada.':'Ferida penetrante no pescoço com sinais de lesão medular: a coluna deve permanecer imobilizada.',
  'Colocar el collarín':'Colocar o colar',
  'Herida penetrante en cuello con signos de lesión medular: inmovilice la columna cervical.':'Ferida penetrante no pescoço com sinais de lesão medular: imobilize a coluna cervical.',
  'Retirar el collarín':'Retirar o colar',
  'Sin indicación de inmovilización por este mecanismo: el collarín puede retirarse.':'Sem indicação de imobilização por este mecanismo: o colar pode ser retirado.',
  'No colocar el collarín':'Não colocar o colar',
  'Sin indicación de inmovilización por este mecanismo: no es necesario colocar collarín.':'Sem indicação de imobilização por este mecanismo: não é necessário colocar colar.',

  /* --- NEXUS --- */
  'Criterios NEXUS':'Critérios NEXUS',
  '¿Se puede liberar la columna cervical? 5 criterios.':'A coluna cervical pode ser liberada? 5 critérios.',
  'NEXUS — Hoffman et al., NEJM 2000 · valoración secundaria, curso MIP':'NEXUS — Hoffman et al., NEJM 2000 · avaliação secundária, curso MIP',
  'Marque los criterios PRESENTES en el paciente. La columna solo se libera si NINGUNO está presente.':'Marque os critérios PRESENTES no paciente. A coluna só é liberada se NENHUM estiver presente.',
  'Dolor en la línea media cervical':'Dor na linha média cervical',
  'Déficit neurológico focal':'Déficit neurológico focal',
  'Estado de alerta anormal (GCS < 14)':'Nível de alerta anormal (ECG < 14)',
  'Intoxicación':'Intoxicação',
  'Lesión distractora':'Lesão distratora',
  'Mantener / colocar la inmovilización cervical':'Manter / colocar a imobilização cervical',
  '{n} de 5 criterios presentes. Con al menos uno positivo, la columna NO puede liberarse; mantenga la inmovilización.':'{n} de 5 critérios presentes. Com pelo menos um positivo, a coluna NÃO pode ser liberada; mantenha a imobilização.',
  'Se puede liberar el collarín':'O colar pode ser retirado',
  '0 de 5 criterios presentes: ningún criterio positivo, la columna cervical puede liberarse.':'0 de 5 critérios presentes: nenhum critério positivo, a coluna cervical pode ser liberada.',

  /* --- Via aérea --- */
  'Evaluación de vía aérea (respuesta verbal)':'Avaliação da via aérea (resposta verbal)',
  'Permeable, obstruida o en riesgo, según la respuesta verbal.':'Pérvia, obstruída ou em risco, conforme a resposta verbal.',
  'Algoritmo MIP — Evaluación 1, Secuencia de Respuesta Verbal (curso MIP, 2026)':'Algoritmo MIP — Avaliação 1, Sequência de Resposta Verbal (curso MIP, 2026)',
  '¿El paciente emite respuesta verbal?':'O paciente emite resposta verbal?',
  'Sí, responde':'Sim, responde','No responde':'Não responde',
  'Calidad de la respuesta:':'Qualidade da resposta:',
  'Coherente':'Coerente','Incoherente':'Incoerente',
  'Características de la voz: ¿hay alteración?':'Características da voz: há alteração?',
  'Disfonía, estridor, voz «apagada» o gorgoteo sugieren lesión de la vía aérea.':'Disfonia, estridor, voz «abafada» ou gorgolejo sugerem lesão da via aérea.',
  'Sí, voz alterada':'Sim, voz alterada','No, voz normal':'Não, voz normal',
  '¿Hay compromiso neurológico?':'Há comprometimento neurológico?',
  'Sí':'Sim','No':'Não',
  '¿Hay obstrucción mecánica de la vía aérea?':'Há obstrução mecânica da via aérea?',
  'Cuerpo extraño, sangre, secreciones, edema o compresión.':'Corpo estranho, sangue, secreções, edema ou compressão.',
  'Vía aérea permeable':'Via aérea pérvia',
  'La vía aérea está permeable en este momento. Continúe con el abordaje primario (B).':'A via aérea está pérvia neste momento. Continue com a abordagem primária (B).',
  'Vía aérea permeable, pero LESIONADA':'Via aérea pérvia, mas LESIONADA',
  'Permeable ahora, pero con signos de lesión.':'Pérvia agora, mas com sinais de lesão.',
  '⚠ Puede evolucionar a obstrucción de la vía aérea asociada a la lesión. REEVALÚE de forma periódica durante la reanimación.':'⚠ Pode evoluir para obstrução da via aérea associada à lesão. REAVALIE periodicamente durante a reanimação.',
  '¡PROTEGER LA VÍA AÉREA!':'PROTEGER A VIA AÉREA!',
  'Respuesta incoherente con compromiso neurológico: la vía aérea está en riesgo. Asegúrela de inmediato.':'Resposta incoerente com comprometimento neurológico: a via aérea está em risco. Assegure-a imediatamente.',
  'Vía aérea OBSTRUIDA':'Via aérea OBSTRUÍDA',
  'Obstrucción mecánica presente: intervención inmediata de la vía aérea.':'Obstrução mecânica presente: intervenção imediata da via aérea.',
  'Sin resultado':'Sem resultado','Revise las respuestas.':'Revise as respostas.'
}
};
